### ISSUE TITLE
Outline View takes a long time to refresh. 

### ISSUE THREAD

**Issue by fujiokae** [eclipse-wildwebdeveloper/wildwebdeveloper#667] opened 2021-04-01 15:55 UTC
I have been using Eclipse PHP with JSDT for a long time but I think JSDT's auto-completion is no longer working with the recent Eclipse (> 2019-03). so I'm considering switching to WWD. There are several issues in WWD compared to JSDT. 

One of them is that it takes a long time to refresh the Outline View. One of my JS file has > 20,000 lines and when I edit it, the Outline View tries to refresh, which takes a long time (several seconds showing "Computing symbols") and makes my typing paused and also the auto-completion proposal takes longer to popup. I don't think it's necessary to refresh the Outline every time I add a new line within a function!

Please speed up the Outline View refresh. Or provide a way to defer the refresh of the View (like a choice of "Manual" or "Auto" refresh). Or please refresh it in a smarter way (e.g. defer refreshing while coding within a function or whenever the user is typing). You may propose to hide the Outline View while coding but I don't want to repeat show/hide the View numerous times.

If this slowness is not addressed, I would be hesitant to switch to WWD and I may have to continue using the old Eclipse with JSDT where the auto-completion still works fine (i.e. Eclipse Mars).

**Comment by mickaelistria** [comment] 2021-04-01 19:16
>  makes my typing paused 

This is not expected. Can you please share a file that allows to reproduce this issue?

**Comment by fujiokae** [comment] 2021-04-01 22:44
Thanks for a quick reply!
For a test purpose, I created an empty project and added the large JS file (mapper_v3.js, zipped and attached here) I reported frequent interruptions while typing on. 
I experienced the same interruptions. When I open it, it would take 8~9 seconds to refresh the Outline View. When I jump to the bottom of the file ([CTRL]+[End]), the codes are not yet colored.
Then I would start typing a new function like:
function test() {
    console.log("....");
    var num = Math.abs(-100);
    console.log(num);
}
My typing (e.g. typing '.' to activate content assistant, adding a new line, deleting characters) is often paused and I have to wait a few seconds. These interruptions happen even when the Outline View is hidden. It is so often and frustrating that I can't use it for my daily development work.

I experienced a similar delay with Eclipse Mars & JSDT but it provided "Include Path" for Javascript where I excluded a large third party Javascript library (an old version of EXTJS), which improved the typing response significantly. I can't find a similar setting in WWD and I don't know how widely and deeply the WWD's content assistant refers to. But in my test, this large library is not included. So, the problem is something else.

Attached is a screenshot when I was deleting characters and got paused.
![2021-04-01 (3)](https://user-images.githubusercontent.com/34692638/113360031-ff7edd80-9316-11eb-8a88-0119bbb61315.png)

[mapper_v3.zip](https://github.com/eclipse/wildwebdeveloper/files/6246745/mapper_v3.zip)

Thanks for investigating in advance.

I use Eclipse PDT package 2021-03 (4.19.0) / Build id: 20210312-0638 on Windows 10 (64 bits) on a HP desktop.
WWD is 0.10.6.

**Comment by mickaelistria** [comment] 2021-04-06 14:32
Thanks.
I could reproduce some "pauses" and looking at the error log, it looks like the issue comes from computation of syntax highlighting that's taking too long and running in the UI Thread. I've opened https://github.com/eclipse/tm4e/issues/275 to track that in the right component (TM4E).

**Comment by fujiokae** [comment] 2021-04-06 21:18
Thanks, Really appreciate it!

**Comment by akurtakov** [comment] 2024-12-13 07:10
Closing as tm4e pr has been merged. Please open new issue with details if you still have problems.

**Closed by akurtakov** 2024-12-13 07:10 UTC
Labels: upstream-tm4e
